default_stages: [commit, push]

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        types: [python]
        language: system
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: uv run ruff check --fix
        types: [python]
        language: system
  - repo: local
    hooks:
      - id: editorconfig
        name: editorconfig
        entry: uv run ec
        types: [python]
        language: system
