"""Generate the API reference Markdown from the live application.

The running server is the source of truth: this renders ``app.openapi()`` (REST)
plus ``machinable.api.protocol`` (WebSocket) into the documentation site's
reference section. Regenerate with::

    python -m machinable.api.docs             # write docs/reference/api/*.md
    python -m machinable.api.docs -o API.md   # single-file snapshot instead
    python -m machinable.api.docs --stdout    # print the single file

Do not hand-edit the output; edit the route/model definitions or
``machinable/api/{openapi,protocol}.py`` and regenerate.
"""

from __future__ import annotations

import os

from machinable.api.protocol import ProtocolDoc, build_protocol

GENERATED_NOTICE = (
    "<!-- GENERATED by `python -m machinable.api.docs` from the live app; "
    "do not edit by hand. -->"
)

_METHOD_ORDER = ["get", "post", "patch", "put", "delete"]


def _escape(text: str | None) -> str:
    """Escape free text for VitePress.

    Raw ``<`` and ``{{`` outside code spans would be parsed as Vue templates;
    ``|`` breaks table cells.
    """
    if not text:
        return ""
    out: list[str] = []
    in_code = False
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "`":
            in_code = not in_code
            out.append(ch)
        elif not in_code and ch == "<":
            out.append("&lt;")
        elif not in_code and text.startswith("{{", i):
            out.append("&#123;&#123;")
            i += 1
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def _cell(text: str | None) -> str:
    return _escape(text).replace("|", "\\|").replace("\n", " ")


def _schema_name(node: dict) -> str | None:
    ref = node.get("$ref")
    if ref:
        return ref.rsplit("/", 1)[-1]
    if node.get("type") == "array" and "items" in node:
        inner = _schema_name(node["items"])
        return f"{inner}[]" if inner else "array"
    return node.get("type")


def _render_parameters(params: list[dict]) -> list[str]:
    lines: list[str] = []
    if not params:
        return lines
    lines.append("")
    lines.append("| Parameter | In | Required | Description |")
    lines.append("|---|---|---|---|")
    for p in params:
        schema = p.get("schema", {})
        typ = _schema_name(schema) or ""
        desc = p.get("description", "") or schema.get("description", "")
        name = f"`{p.get('name', '')}`"
        if typ:
            name = f"{name} ({_cell(typ)})"
        lines.append(
            f"| {name} | {p.get('in', '')} | "
            f"{'yes' if p.get('required') else 'no'} | {_cell(desc)} |"
        )
    return lines


def _schema_link(name: str, prefix: str) -> str:
    return f"[`{name}`]({prefix}#{name.lower().strip('[]')})"


def _render_request_body(body: dict, schema_prefix: str = "") -> list[str]:
    content = body.get("content", {}).get("application/json", {})
    name = _schema_name(content.get("schema", {}))
    if not name:
        return []
    required = " (required)" if body.get("required") else ""
    return ["", f"**Request body:** {_schema_link(name, schema_prefix)}{required}"]


def _render_responses(responses: dict, schema_prefix: str = "") -> list[str]:
    lines = ["", "**Responses:**"]
    for status, resp in sorted(responses.items()):
        content = resp.get("content", {}).get("application/json", {})
        name = _schema_name(content.get("schema", {}))
        ref = f" → {_schema_link(name, schema_prefix)}" if name else ""
        lines.append(f"- `{status}` {_escape(resp.get('description', ''))}{ref}")
    return lines


def _render_rest(openapi: dict, schema_prefix: str = "") -> list[str]:
    lines = ["## REST endpoints", ""]
    tags = [t["name"] for t in openapi.get("tags", [])]
    tag_desc = {t["name"]: t.get("description", "") for t in openapi.get("tags", [])}

    # group operations by their first tag, preserving the declared tag order
    by_tag: dict[str, list[tuple[str, str, dict]]] = {t: [] for t in tags}
    for path, item in openapi.get("paths", {}).items():
        for method in _METHOD_ORDER:
            if method not in item:
                continue
            op = item[method]
            tag = (op.get("tags") or ["other"])[0]
            by_tag.setdefault(tag, []).append((path, method, op))

    for tag in list(by_tag.keys()):
        ops = by_tag.get(tag) or []
        if not ops:
            continue
        lines.append(f"### {tag}")
        if tag_desc.get(tag):
            lines.append("")
            lines.append(_escape(tag_desc[tag]))
        for path, method, op in ops:
            lines.append("")
            summary = op.get("summary") or op.get("operationId", "")
            lines.append(f"#### `{method.upper()} {path}`")
            if summary:
                lines.append("")
                lines.append(f"_{_escape(summary)}_")
            desc = op.get("description")
            if desc and desc != summary:
                lines.append("")
                lines.append(_escape(desc.strip()))
            lines += _render_parameters(op.get("parameters", []))
            if "requestBody" in op:
                lines += _render_request_body(op["requestBody"], schema_prefix)
            lines += _render_responses(op.get("responses", {}), schema_prefix)
        lines.append("")
    return lines


def _render_protocol(proto: ProtocolDoc) -> list[str]:
    lines = [
        "## WebSocket protocol",
        "",
        f"Protocol version **{proto.protocol_version}**. Served live and "
        "machine-readable at `GET /v1/protocol`.",
        "",
        "**Transport**",
    ]
    for key, val in proto.transport.items():
        lines.append(f"- `{key}`: {_escape(val)}")

    lines += ["", "**Endpoints**"]
    for route, desc in proto.ws_endpoints.items():
        lines.append(f"- `{route}`: {_escape(desc)}")

    lines += ["", "**Request headers**", ""]
    lines.append("| Header | Required | Description |")
    lines.append("|---|---|---|")
    for h in proto.headers:
        lines.append(
            f"| `{h.name}` | {'yes' if h.required else 'no'} | {_cell(h.description)} |"
        )

    lines += ["", "**Frames**", ""]
    lines.append("| `type` | Direction | Purpose |")
    lines.append("|---|---|---|")
    for f in proto.ws_frames:
        lines.append(f"| `{f.type}` | {f.direction} | {_cell(f.summary)} |")
    for f in proto.ws_frames:
        if not f.fields:
            continue
        lines += ["", f"`{f.type}` fields:"]
        for field in f.fields:
            req = " (required)" if field.required else ""
            lines.append(
                f"- `{field.name}` ({field.type}){req}: {_escape(field.description)}"
            )

    lines += ["", "**Binary flows**"]
    for flow in proto.chunk_flows:
        lines += ["", f"_{flow.name}_: {_escape(flow.summary)}", "", "```"]
        lines += list(flow.sequence)
        lines.append("```")

    lines += ["", "## Interface hooks", "", "Implemented by project interfaces:"]
    for hook in proto.interface_hooks:
        lines += ["", f"#### `{hook.name}`", ""]
        lines += [f"```python\n{hook.signature}\n```", ""]
        lines.append(_escape(hook.description))

    lines += ["", "## Capabilities", ""]
    lines += ["| Capability | Summary | Surfaces |", "|---|---|---|"]
    for cap in proto.capabilities:
        surfaces = "; ".join(f"`{s}`" for s in cap.surfaces)
        lines.append(f"| **{cap.name}** | {_cell(cap.summary)} | {surfaces} |")
    return lines


def _render_schemas(openapi: dict) -> list[str]:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = ["## Schemas", ""]
    for name in sorted(schemas):
        schema = schemas[name]
        lines.append(f"### {name}")
        if schema.get("description"):
            lines.append("")
            lines.append(_escape(schema["description"].strip()))
        props = schema.get("properties")
        if props:
            required = set(schema.get("required", []))
            lines += ["", "| Field | Type | Req | Description |", "|---|---|---|---|"]
            for field, node in props.items():
                typ = _schema_name(node) or "any"
                desc = node.get("description", "")
                lines.append(
                    f"| `{field}` | {_cell(typ)} | "
                    f"{'yes' if field in required else 'no'} | {_cell(desc)} |"
                )
        elif "enum" in schema:
            lines += ["", "Enum: " + ", ".join(f"`{v}`" for v in schema["enum"])]
        lines.append("")
    return lines


def render(app=None) -> str:
    """Render the full API reference as a single Markdown document."""
    if app is None:
        from machinable.api.app import create_app

        app = create_app()
    openapi = app.openapi()
    proto = build_protocol()
    info = openapi.get("info", {})

    lines = [
        GENERATED_NOTICE,
        "",
        f"# {info.get('title', 'machinable API')} (v{info.get('version', '')})",
        "",
        _escape(info.get("summary", "")),
        "",
        _escape(info.get("description", "")),
        "",
    ]
    lines += _render_rest(openapi)
    lines += _render_protocol(proto)
    lines += [""]
    lines += _render_schemas(openapi)
    return "\n".join(lines).rstrip() + "\n"


def render_site_pages(app=None) -> dict[str, str]:
    """Render the reference as site pages: ``{filename: content}``.

    Three pages under the documentation site's reference section: the REST
    endpoints, the WebSocket protocol, and the schemas.
    """
    if app is None:
        from machinable.api.app import create_app

        app = create_app()
    openapi = app.openapi()
    proto = build_protocol()
    info = openapi.get("info", {})

    def page(title_lines: list[str], body: list[str]) -> str:
        lines = [GENERATED_NOTICE, "", *title_lines, "", *body]
        return "\n".join(lines).rstrip() + "\n"

    endpoints = page(
        [
            f"# HTTP endpoints (v{info.get('version', '')})",
            "",
            _escape(info.get("summary", "")),
            "",
            _escape(info.get("description", "")),
        ],
        _render_rest(openapi, schema_prefix="./schemas"),
    )
    ws = page(["# WebSocket protocol"], _render_protocol(proto)[1:])
    schemas = page(["# Schemas"], _render_schemas(openapi)[1:])
    return {
        "endpoints.md": endpoints,
        "ws-protocol.md": ws,
        "schemas.md": schemas,
    }


def _docs_root() -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(here, "..", "..", "..", "docs"))


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate the API reference.")
    parser.add_argument(
        "--stdout", action="store_true", help="Print the single-file rendering."
    )
    parser.add_argument(
        "-o", "--output", default=None, help="Write a single-file snapshot instead."
    )
    args = parser.parse_args(argv)

    if args.stdout:
        print(render())
        return 0
    if args.output:
        content = render()
        os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(content)
        print(f"wrote {args.output} ({len(content)} bytes)")
        return 0

    out_dir = os.path.join(_docs_root(), "reference", "api")
    os.makedirs(out_dir, exist_ok=True)
    for filename, content in render_site_pages().items():
        with open(os.path.join(out_dir, filename), "w", encoding="utf-8") as handle:
            handle.write(content)
        print(f"wrote reference/api/{filename} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
