ClusterName=machinable
SlurmctldHost=machinable-slurm
SlurmUser=root
SlurmdUser=root
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
ReturnToService=2
SlurmdParameters=config_overrides
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdLogFile=/var/log/slurmd.log
NodeName=machinable-slurm CPUs=2 RealMemory=512 State=UNKNOWN
PartitionName=development Nodes=ALL Default=YES MaxTime=INFINITE State=UP
