#!/usr/bin/env python3

"""Generate the integrations library pages as static markdown.

Reads ``integrations/*/integration.yaml`` and emits one page per integration
plus a filterable index into ``docs/integrations/`` (gitignored; regenerated by
``npm run gen`` before dev/build) and a sidebar manifest. Config tables are
parsed from the module's AST so the docs build never imports integration
dependencies.

Usage::

    uv run .vitepress/integrationsgen.py             # write the pages + sidebar
    uv run .vitepress/integrationsgen.py --validate  # check metadata (used by CI)
"""

import ast
import json
import os
import subprocess
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
SRC_DIR = os.path.join(ROOT, "integrations")
OUT_DIR = os.path.join(ROOT, "docs", "integrations")
SIDEBAR = os.path.join(ROOT, "docs", ".vitepress", "sidebar-integrations.json")
REPO_URL = "https://github.com/machinable-org/machinable"

STATUSES = ("active", "archived")
REQUIRED_FIELDS = ("name", "summary", "maintainer", "status")

DISCLAIMER = (
    "::: warning Community-maintained\n"
    "Integrations are not part of machinable core: they are not covered by the "
    "core test suite or releases and come with no maintenance guarantee. "
    "Issues go to each integration's maintainer. See the "
    f"[policy and contribution process]({REPO_URL}/blob/main/integrations/README.md). "
    "Pulled modules [execute arbitrary code on import]"
    "(/guide/storage#remotes-shareable-interfaces), so review what you pull "
    "(`machinable fetch <name>` downloads without importing).\n"
    ":::"
)


def _git_ref():
    """The ref install snippets pin to (see pydocgen._git_ref)."""
    ref = os.environ.get("MACHINABLE_DOCS_REF")
    if ref:
        return ref
    try:
        return (
            subprocess.check_output(
                ["git", "-C", ROOT, "rev-parse", "HEAD"],
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
    except Exception:
        return "main"


def discover():
    """All integrations as ``(directory, metadata)``, sorted by name."""
    found = []
    for entry in sorted(os.listdir(SRC_DIR)):
        directory = os.path.join(SRC_DIR, entry)
        manifest = os.path.join(directory, "integration.yaml")
        if os.path.isfile(manifest):
            with open(manifest, encoding="utf-8") as f:
                found.append((directory, yaml.safe_load(f)))
    return found


def check(directory, meta):
    """The integration's schema/layout errors (empty when valid)."""
    errors = []
    slug = os.path.basename(directory)
    for field in REQUIRED_FIELDS:
        if not meta.get(field):
            errors.append(f"missing field '{field}'")
    if meta.get("name") != slug:
        errors.append(f"name '{meta.get('name')}' must match directory '{slug}'")
    tags = meta.get("tags")
    if not (isinstance(tags, list) and tags and all(isinstance(t, str) for t in tags)):
        errors.append("tags must be a non-empty list of strings (the classification)")
    url = meta.get("maintainer_url")
    if url is not None and not str(url).startswith(("http://", "https://")):
        errors.append("maintainer_url must be an http(s) URL")
    if meta.get("status") not in STATUSES:
        errors.append(f"status must be one of {STATUSES}")
    if not os.path.isfile(os.path.join(directory, f"{slug}.py")):
        errors.append(f"missing module {slug}.py")
    if not os.path.isfile(os.path.join(directory, "README.md")):
        errors.append("missing README.md")
    if not any(f.startswith("test_") for f in os.listdir(directory)):
        errors.append("missing test file (test_*.py)")
    return errors


def config_fields(module_path):
    """``(field, annotation, default)`` rows of the first interface's Config.

    Parsed from the AST so heavy integration dependencies are never imported.
    """
    tree = ast.parse(open(module_path, encoding="utf-8").read())
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        for child in node.body:
            if isinstance(child, ast.ClassDef) and child.name == "Config":
                rows = []
                for stmt in child.body:
                    if isinstance(stmt, ast.AnnAssign) and isinstance(
                        stmt.target, ast.Name
                    ):
                        rows.append(
                            (
                                stmt.target.id,
                                ast.unparse(stmt.annotation),
                                ast.unparse(stmt.value) if stmt.value else None,
                            )
                        )
                return rows
    return []


def render_config_table(module_path):
    rows = config_fields(module_path)
    if not rows:
        return []
    lines = [
        "## Configuration",
        "",
        "| Option | Type | Default |",
        "| --- | --- | --- |",
    ]

    def cell(s):
        return "`" + s.replace("|", "\\|") + "`" if s else "*required*"

    for name, annotation, default in rows:
        if name == "model_config":
            continue
        lines.append(f"| `{name}` | {cell(annotation)} | {cell(default)} |")
    lines.append("")
    return lines


def render_page(directory, meta, ref):
    slug = meta["name"]
    raw_url = f"https://raw.githubusercontent.com/machinable-org/machinable/{ref}/integrations/{slug}/{slug}.py"
    lines = [
        "<!-- GENERATED by `npm run gen` (.vitepress/integrationsgen.py) — do not edit. -->",
        "",
        f"# {slug}",
        "",
        " · ".join(
            [
                " ".join(f"`{tag}`" for tag in meta["tags"]),
                "maintainer "
                + (
                    f"[{meta['maintainer']}]({meta['maintainer_url']})"
                    if meta.get("maintainer_url")
                    else str(meta["maintainer"])
                ),
            ]
            + ([f"[upstream]({meta['upstream']})"] if meta.get("upstream") else [])
            + (["**archived**"] if meta["status"] == "archived" else [])
        ),
        "",
        meta["summary"] + ".",
        "",
        "## Install",
        "",
        "Declare the remote in your project's provider; the module is fetched on"
        " first use:",
        "",
        "```python",
        "# interface/project.py — your project's provider",
        "from machinable import Project",
        "",
        "",
        "class MyProject(Project):",
        "    def on_resolve_remotes(self):",
        "        return {",
        f'            "{slug}": "url+{raw_url}",',
        "        }",
        "```",
    ]
    if meta.get("requires"):
        deps = " ".join(meta["requires"])
        lines += ["", f"Runtime dependencies: `pip install {deps}`"]
    lines += [
        "",
        f"The module is fetched once and cached in `interface/remotes/`;"
        f" `machinable fetch {slug}` downloads it without importing so you can"
        " inspect the code first. See"
        " [Resolving remotes](/guide/storage#remotes-shareable-interfaces) for"
        " how pulling, pinning, and updating work.",
        "",
    ]
    readme = os.path.join(directory, "README.md")
    lines += [open(readme, encoding="utf-8").read().strip(), ""]
    lines += render_config_table(os.path.join(directory, f"{slug}.py"))
    # OUT_DIR is docs/integrations, so the module sits two levels up
    lines += [
        "## Source",
        "",
        f"[integrations/{slug}/{slug}.py]({REPO_URL}/blob/{ref}/integrations/{slug}/{slug}.py)",
        "",
        f"::: details `{slug}.py`",
        f"<<< ../../integrations/{slug}/{slug}.py{{py:line-numbers}}",
        ":::",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_index(integrations):
    cards = [
        {
            "name": meta["name"],
            "summary": meta["summary"],
            "tags": meta["tags"],
            "archived": meta["status"] == "archived",
            "link": f"/integrations/{meta['name']}",
        }
        for _, meta in integrations
    ]
    data = json.dumps(cards, indent=2)
    return f"""<!-- GENERATED by `npm run gen` (.vitepress/integrationsgen.py) — do not edit. -->

# Integrations

Community-maintained interfaces you can pull into a project by URL: execution
backends, storage adapters, and reusable components. Each page has a copy-paste
install snippet, and adding your own is a single pull request.

{DISCLAIMER}

<script setup>
import {{ ref, computed }} from 'vue'

const items = {data}

const query = ref('')
const tag = ref('')
// only tags shared by more than one integration are useful as filters
const counts = items.flatMap(i => i.tags).reduce((m, t) => (m[t] = (m[t] || 0) + 1, m), {{}})
const sharedTags = Object.keys(counts).filter(t => counts[t] > 1).sort()
const filtered = computed(() =>
  items.filter(i =>
    (!tag.value || i.tags.includes(tag.value)) &&
    (i.name + ' ' + i.summary + ' ' + i.tags.join(' '))
      .toLowerCase()
      .includes(query.value.toLowerCase())
  )
)
</script>

<div class="int-controls">
  <input class="int-search" v-model="query" placeholder="Filter…" />
  <button
    v-for="t in sharedTags"
    :key="t"
    class="int-chip"
    :class="{{ active: tag === t }}"
    @click="tag = tag === t ? '' : t"
  >{{{{ t }}}}</button>
</div>

<div class="int-grid">
  <a v-for="i in filtered" :key="i.name" :href="i.link" class="int-card" :class="{{ archived: i.archived }}">
    <div class="int-card-head">
      <strong>{{{{ i.name }}}}</strong>
      <span v-if="i.archived" class="int-badge archived">archived</span>
    </div>
    <p>{{{{ i.summary }}}}</p>
    <div class="int-card-tags">
      <span v-for="t in i.tags" :key="t" class="int-badge">{{{{ t }}}}</span>
    </div>
  </a>
  <p v-if="!filtered.length" class="int-empty">No integration matches.</p>
</div>

<style scoped>
.int-controls {{ display: flex; gap: 8px; align-items: center; margin: 24px 0 16px; flex-wrap: wrap; }}
.int-search {{ flex: 1; min-width: 180px; padding: 6px 12px; border: 1px solid var(--vp-c-divider); border-radius: 8px; background: var(--vp-c-bg); }}
.int-chip {{ padding: 4px 12px; border: 1px solid var(--vp-c-divider); border-radius: 999px; font-size: 13px; }}
.int-chip.active {{ border-color: var(--vp-c-brand-1); color: var(--vp-c-brand-1); }}
.int-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px; }}
.int-card {{ display: block; padding: 14px 16px; border: 1px solid var(--vp-c-divider); border-radius: 10px; background: var(--vp-c-bg-soft); text-decoration: none; color: inherit; transition: border-color 0.2s; }}
.int-card:hover {{ border-color: var(--vp-c-brand-1); }}
.int-card.archived {{ opacity: 0.55; }}
.int-card-head {{ display: flex; gap: 8px; align-items: center; }}
.int-card p {{ margin: 6px 0 0; font-size: 13px; color: var(--vp-c-text-2); line-height: 1.5; }}
.int-card-tags {{ display: flex; gap: 4px; flex-wrap: wrap; margin-top: 10px; }}
.int-badge {{ font-size: 11px; padding: 1px 8px; border-radius: 999px; background: var(--vp-c-default-soft); }}
.int-badge.archived {{ background: var(--vp-c-warning-soft); }}
.int-empty {{ color: var(--vp-c-text-2); }}
</style>
"""


def generate():
    integrations = discover()
    problems = {d: check(d, m) for d, m in integrations}
    if any(problems.values()):
        report(problems)
        sys.exit(1)
    ref = _git_ref()
    os.makedirs(OUT_DIR, exist_ok=True)
    entries = [{"text": "Overview", "link": "/integrations/"}]
    for directory, meta in integrations:
        with open(
            os.path.join(OUT_DIR, f"{meta['name']}.md"), "w", encoding="utf-8"
        ) as f:
            f.write(render_page(directory, meta, ref))
        entries.append({"text": meta["name"], "link": f"/integrations/{meta['name']}"})
        print(f"  wrote integrations/{meta['name']}.md")
    with open(os.path.join(OUT_DIR, "index.md"), "w", encoding="utf-8") as f:
        f.write(render_index(integrations))
    print("  wrote integrations/index.md")
    sidebar = [{"text": "Integrations", "items": entries}]
    with open(SIDEBAR, "w", encoding="utf-8") as f:
        json.dump(sidebar, f, indent=2)
    print(f"  wrote {os.path.relpath(SIDEBAR, ROOT)}")


def report(problems):
    for directory, errors in problems.items():
        for error in errors:
            print(f"  {os.path.relpath(directory, ROOT)}: {error}")


def validate():
    integrations = discover()
    problems = {d: check(d, m) for d, m in integrations}
    count = sum(len(e) for e in problems.values())
    if count:
        print(f"ERROR: {count} metadata problem(s):")
        report(problems)
        sys.exit(1)
    print(f"OK: {len(integrations)} integration(s) valid")


if __name__ == "__main__":
    if "--validate" in sys.argv:
        validate()
    else:
        generate()
