#!/usr/bin/env python3

"""Generate the Python API reference as static markdown pages.

Emits one page per public symbol group into ``docs/reference/python/`` (gitignored;
regenerated by ``npm run gen`` before dev/build) plus a sidebar manifest the VitePress
config reads. Static pages are pre-rendered and indexed by the local search; each
method gets a stable ``### heading`` anchor for deep links.

Usage::

    uv run .vitepress/pydocgen.py             # write the pages + sidebar
    uv run .vitepress/pydocgen.py --validate  # check /reference/python links in docs
"""

import inspect
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
OUT_DIR = os.path.join(ROOT, "docs", "reference", "python")
SIDEBAR = os.path.join(ROOT, "docs", ".vitepress", "sidebar-reference.json")
REPO_URL = "https://github.com/machinable-org/machinable"

sys.path.insert(0, os.path.join(ROOT, "src"))


def _git_ref():
    """The ref GitHub source permalinks pin to.

    The build-time commit sha, so line links match the code the pages were
    generated from. Overridable via MACHINABLE_DOCS_REF (e.g. a tag); falls
    back to ``main`` when git is unavailable. Note that sha links resolve on
    GitHub only once the commit is pushed.
    """
    import subprocess

    ref = os.environ.get("MACHINABLE_DOCS_REF")
    if ref:
        return ref
    try:
        return (
            subprocess.check_output(
                ["git", "-C", ROOT, "rev-parse", "HEAD"],
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
    except Exception:
        return "main"


GIT_REF = _git_ref()


def source_ref(obj):
    """``(repo-relative path, start line, end line, github url)`` or None."""
    try:
        file = inspect.getsourcefile(obj)
        lines, start = inspect.getsourcelines(obj)
    except (TypeError, OSError):
        return None
    if file is None:
        return None
    rel = os.path.relpath(file, ROOT).replace(os.sep, "/")
    end = start + len(lines) - 1
    url = f"{REPO_URL}/blob/{GIT_REF}/{rel}#L{start}-L{end}"
    return rel, start, end, url


def pages():
    """The curated public surface: (slug, title, [objects])."""
    import machinable
    from machinable import collection, config

    return [
        ("interface", "Interface", [machinable.Interface]),
        ("execution", "Execution", [machinable.Execution]),
        ("inference", "Inference", [machinable.Inference]),
        ("widget", "Widget", [machinable.Widget]),
        ("project", "Project", [machinable.Project]),
        ("storage", "Storage", [machinable.Storage]),
        # the class is named Index; "catalog" avoids an index.md filename
        ("catalog", "Index", [machinable.Index]),
        ("scope", "Scope", [machinable.Scope]),
        ("query", "Query", [machinable.Query]),
        (
            "collections",
            "Collections",
            [
                collection.Collection,
                collection.InterfaceCollection,
                collection.ExecutionCollection,
            ],
        ),
        (
            "helpers",
            "Helpers",
            [
                config.Field,
                config.import_ref,
                config.resolve_ref,
                config.predicate_from_manifest,
                machinable.from_cli,
            ],
        ),
    ]


def escape(text):
    """Make free text safe for VitePress (Vue parses raw ``<`` and ``{{``)."""
    if not text:
        return text
    out = []
    in_code = False
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "`":
            in_code = not in_code
            out.append(ch)
        elif not in_code and ch == "<":
            out.append("&lt;")
        elif not in_code and text.startswith("{{", i):
            out.append("&#123;&#123;")
            i += 1
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def docstring(obj):
    doc = inspect.getdoc(obj)
    if not doc:
        return None
    # docstrings use RST markup: ``x`` code spans and :meth:`x` / :func:`x` roles
    doc = doc.replace("``", "`")
    doc = re.sub(r":(?:meth|func|class|attr|mod):`~?([^`]+)`", r"`\1`", doc)
    return escape(doc.strip())


def signature(obj):
    try:
        return str(inspect.signature(obj))
    except (ValueError, TypeError):
        return None


def own_members(cls):
    """Public routines and properties defined on ``cls`` itself (not inherited)."""
    members = []
    for name, value in sorted(vars(cls).items()):
        if name.startswith("_"):
            continue
        if isinstance(value, (classmethod, staticmethod)):
            members.append((name, value.__func__, "method"))
        elif isinstance(value, property):
            members.append((name, value.fget, "property"))
        elif inspect.isfunction(value):
            members.append((name, value, "method"))
    return members


def _member_source_link(fn):
    ref = source_ref(fn)
    if ref is None:
        return []
    rel, start, end, url = ref
    return [
        f'<div class="source-ref"><a href="{url}" target="_blank" '
        f'rel="noreferrer">{rel}:{start}</a></div>',
        "",
    ]


def render_class(cls, level=1):
    lines = []
    h = "#" * level
    lines.append(f"{h} {cls.__name__}")
    lines.append("")
    bases = [b.__name__ for b in cls.__bases__ if b.__name__ != "object"]
    inherits = f" (inherits `{', '.join(bases)}`)" if bases else ""
    ref = source_ref(cls)
    src = (
        f' · <a href="{ref[3]}" target="_blank" rel="noreferrer">source</a>'
        if ref
        else ""
    )
    lines.append(f"`{cls.__module__}.{cls.__name__}`{inherits}{src}")
    lines.append("")
    doc = docstring(cls)
    if doc:
        lines.append(doc)
        lines.append("")

    config_cls = vars(cls).get("Config")
    if inspect.isclass(config_cls) and hasattr(config_cls, "model_fields"):
        lines.append(f"{h}# Config")
        lines.append("")
        lines.append("| Field | Type | Default |")
        lines.append("| --- | --- | --- |")
        for name, field in config_cls.model_fields.items():
            if field.is_required():
                default = "*required*"
            elif field.default_factory is not None:
                default = "*computed*"
            else:
                default = f"`{field.default!r}`"
            annotation = f"`{field.annotation}`"
            annotation = escape(annotation.replace("<class '", "`").replace("'>", "`"))
            # union-type pipes would split the table cell
            annotation = annotation.replace("|", "\\|")
            lines.append(f"| `{name}` | {annotation} | {default} |")
        lines.append("")

    for name, fn, kind in own_members(cls):
        heading = "#" * (level + 1)
        suffix = "" if kind == "property" else "()"
        lines.append(f"{heading} {name}{suffix}")
        lines.append("")
        lines += _member_source_link(fn)
        sig = signature(fn)
        if sig and kind != "property":
            lines.append("```python")
            lines.append(f"{name}{sig}")
            lines.append("```")
            lines.append("")
        doc = docstring(fn)
        if doc:
            lines.append(doc)
            lines.append("")
    return lines


def render_routine(fn, level=1):
    lines = []
    lines.append(f"{'#' * level} {fn.__name__}()")
    lines.append("")
    lines.append(f"`{fn.__module__}.{fn.__name__}`")
    lines.append("")
    lines += _member_source_link(fn)
    sig = signature(fn)
    if sig:
        lines.append("```python")
        lines.append(f"{fn.__name__}{sig}")
        lines.append("```")
        lines.append("")
    doc = docstring(fn)
    if doc:
        lines.append(doc)
        lines.append("")
    return lines


def source_files(objects):
    """Unique repo-relative source files behind ``objects``, in first-seen order."""
    seen = []
    for obj in objects:
        try:
            f = inspect.getsourcefile(obj)
        except TypeError:
            continue
        if f is None:
            continue
        rel = os.path.relpath(f, ROOT).replace(os.sep, "/")
        if rel not in seen:
            seen.append(rel)
    return seen


def render_source_section(objects):
    """A collapsed, line-numbered source include per contributing module.

    Uses the VitePress code-snippet import (``<<< path``), so the source shown
    is read from disk at build time.
    """
    files = source_files(objects)
    if not files:
        return []
    lines = ["## Source", ""]
    for rel in files:
        include = "/".join([".."] * 3) + "/" + rel  # OUT_DIR is docs/reference/python
        lines += [
            f"::: details `{rel}`",
            f"<<< {include}{{py:line-numbers}}",
            ":::",
            "",
        ]
    return lines


def render_page(slug, title, objects):
    lines = [
        "<!-- GENERATED by `npm run gen` (.vitepress/pydocgen.py) — do not edit. -->",
        "",
    ]
    if len(objects) == 1:
        obj = objects[0]
        if inspect.isclass(obj):
            lines += render_class(obj, level=1)
        else:
            lines += render_routine(obj, level=1)
    else:
        lines.append(f"# {title}")
        lines.append("")
        for obj in objects:
            if inspect.isclass(obj):
                lines += render_class(obj, level=2)
            else:
                lines += render_routine(obj, level=2)
    lines += render_source_section(objects)
    return "\n".join(lines).rstrip() + "\n"


def generate():
    os.makedirs(OUT_DIR, exist_ok=True)
    sidebar = []
    for slug, title, objects in pages():
        content = render_page(slug, title, objects)
        with open(os.path.join(OUT_DIR, f"{slug}.md"), "w", encoding="utf-8") as f:
            f.write(content)
        sidebar.append({"text": title, "link": f"/reference/python/{slug}"})
        print(f"  wrote reference/python/{slug}.md")
    with open(SIDEBAR, "w", encoding="utf-8") as f:
        json.dump(sidebar, f, indent=2)
    print(f"  wrote {os.path.relpath(SIDEBAR, ROOT)}")


def validate():
    """Check that /reference/python/<slug> links used across the docs resolve."""
    import glob

    slugs = {slug for slug, _, _ in pages()}
    pattern = re.compile(r"/reference/python/([a-z0-9-]+)")
    errors = []
    for md_file in glob.glob(os.path.join(ROOT, "docs", "**", "*.md"), recursive=True):
        if os.sep + "node_modules" + os.sep in md_file:
            continue
        with open(md_file, encoding="utf-8") as f:
            for lineno, line in enumerate(f, 1):
                for match in pattern.finditer(line):
                    if match.group(1) not in slugs:
                        rel = os.path.relpath(md_file, ROOT)
                        errors.append(f"  {rel}:{lineno}: {match.group(0)}")
    if errors:
        print(f"ERROR: {len(errors)} unresolved reference link(s):")
        print("\n".join(errors))
        sys.exit(1)
    print(f"OK: all /reference/python links resolve ({len(slugs)} pages)")


if __name__ == "__main__":
    if "--validate" in sys.argv:
        validate()
    else:
        generate()
