name: Documentation build and publish 📝
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Set up cache
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --extras "integrations server"
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Autogenerate reference documentation
        run: |
          source .venv/bin/activate
          python docs/.vuepress/_reference/autogen.py
      - name: Build and Deploy
        uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: docs/.vuepress/dist
          BUILD_SCRIPT: npm install vuepress && /github/workspace/node_modules/vuepress build docs
